#pragma once

extern "C"

dim shared ABS_ as long
dim shared ABSTRACT_ as long
dim shared ACCESS_ as long
dim shared ACOS_ as long
dim shared ALIAS_ as long
dim shared ALLOCATE_ as long
dim shared AND_ as long
dim shared ANDALSO_ as long
dim shared ANY_ as long
dim shared APPEND_ as long
dim shared AS_ as long
dim shared ASC_ as long
dim shared ASIN_ as long
dim shared ASM_ as long
dim shared ASSERT_ as long
dim shared ASSERTWARN_ as long
dim shared ATAN2_ as long
dim shared ATN_ as long
dim shared BASE_ as long
dim shared BEEP_ as long
dim shared BIN_ as long
dim shared BINARY_ as long
dim shared BIT_ as long
dim shared BITRESET_ as long
dim shared BITSET_ as long
dim shared BLOAD_ as long
dim shared BSAVE_ as long
dim shared BYREF_ as long
dim shared BYTE_ as long
dim shared BYVAL_ as long
dim shared CALL_ as long
dim shared CALLOCATE_ as long
dim shared CASE_ as long
dim shared CAST_ as long
dim shared CBYTE_ as long
dim shared CDBL_ as long
dim shared CDECL_ as long
dim shared CHAIN_ as long
dim shared CHDIR_ as long
dim shared CHR_ as long
dim shared CINT_ as long
dim shared CIRCLE_ as long
dim shared CLASS_ as long
dim shared CLEAR_ as long
dim shared CLNG_ as long
dim shared CLNGINT_ as long
dim shared CLOSE_ as long
dim shared CLS_ as long
dim shared COLOR_ as long
dim shared COMMAND_ as long
dim shared COMMON_ as long
dim shared CONDBROADCAST_ as long
dim shared CONDCREATE_ as long
dim shared CONDDESTROY_ as long
dim shared CONDSIGNAL_ as long
dim shared CONDWAIT_ as long
dim shared CONST_ as long
dim shared CONSTRUCTOR_ as long
dim shared CONTINUE_ as long
dim shared COS_ as long
dim shared CPTR_ as long
dim shared CSHORT_ as long
dim shared CSIGN_ as long
dim shared CSNG_ as long
dim shared CSRLIN_ as long
dim shared CUBYTE_ as long
dim shared CUINT_ as long
dim shared CULNG_ as long
dim shared CULNGINT_ as long
dim shared CUNSG_ as long
dim shared CURDIR_ as long
dim shared CUSHORT_ as long
dim shared CVD_ as long
dim shared CVI_ as long
dim shared CVL_ as long
dim shared CVLONGINT_ as long
dim shared CVS_ as long
dim shared CVSHORT_ as long
dim shared DATA_ as long
dim shared DATE_ as long
dim shared DEALLOCATE_ as long
dim shared DECLARE_ as long
dim shared DEFBYTE_ as long
dim shared DEFDBL_ as long
dim shared DEFINE_ as long
dim shared DEFINED_ as long
dim shared DEFINT_ as long
dim shared DEFLNG_ as long
dim shared DEFLONGINT_ as long
dim shared DEFSHORT_ as long
dim shared DEFSNG_ as long
dim shared DEFSTR_ as long
dim shared DEFUBYTE_ as long
dim shared DEFUINT_ as long
dim shared DEFULNG_ as long
dim shared DEFULONGINT_ as long
dim shared DEFUSHORT_ as long
dim shared DELETE_ as long
dim shared DESTRUCTOR_ as long
dim shared DIM_ as long
dim shared DIR_ as long
dim shared DO_ as long
dim shared DOUBLE_ as long
dim shared DRAW_ as long
dim shared DYLIBFREE_ as long
dim shared DYLIBLOAD_ as long
dim shared DYLIBSYMBOL_ as long
dim shared DYNAMIC_ as long
dim shared ELSE_ as long
dim shared ELSEIF_ as long
dim shared ENCODING_ as long
dim shared END_ as long
dim shared ENDIF_ as long
dim shared ENDMACRO_ as long
dim shared ENUM_ as long
dim shared ENVIRON_ as long
dim shared EOF_ as long
dim shared EQV_ as long
dim shared ERASE_ as long
dim shared ERFN_ as long
dim shared ERL_ as long
dim shared ERMN_ as long
dim shared ERR_ as long
dim shared ERROR_ as long
dim shared EXEC_ as long
dim shared EXEPATH_ as long
dim shared EXIT_ as long
dim shared EXP_ as long
dim shared EXPLICIT_ as long
dim shared EXPORT_ as long
dim shared EXTENDS_ as long
dim shared EXTERN_ as long
dim shared FIELD_ as long
dim shared FIX_ as long
dim shared FLIP_ as long
dim shared FOR_ as long
dim shared FRAC_ as long
dim shared FRE_ as long
dim shared FREEFILE_ as long
dim shared FUNCTION_ as long
dim shared GET_ as long
dim shared GETJOYSTICK_ as long
dim shared GETKEY_ as long
dim shared GETMOUSE_ as long
dim shared GOSUB_ as long
dim shared GOTO_ as long
dim shared HEX_ as long
dim shared HIBYTE_ as long
dim shared HIWORD_ as long
dim shared IF_ as long
dim shared IFDEF_ as long
dim shared IFNDEF_ as long
dim shared IIF_ as long
dim shared IMAGECONVERTROW_ as long
dim shared IMAGECREATE_ as long
dim shared IMAGEDESTROY_ as long
dim shared IMAGEINFO_ as long
dim shared IMP_ as long
dim shared IMPLEMENTS_ as long
dim shared IMPORT_ as long
dim shared INCLIB_ as long
dim shared INCLUDE_ as long
dim shared INKEY_ as long
dim shared INP_ as long
dim shared INPUT_ as long
dim shared INSTR_ as long
dim shared INSTRREV_ as long
dim shared INT_ as long
dim shared INTEGER_ as long
dim shared IS_ as long
dim shared KILL_ as long
dim shared LANG_ as long
dim shared LBOUND_ as long
dim shared LCASE_ as long
dim shared LEFT_ as long
dim shared LEN_ as long
dim shared LET_ as long
dim shared LIB_ as long
dim shared LIBPATH_ as long
dim shared LINE_ as long
dim shared LOBYTE_ as long
dim shared LOC_ as long
dim shared LOCAL_ as long
dim shared LOCATE_ as long
dim shared LOCK_ as long
dim shared LOF_ as long
dim shared LOG_ as long
dim shared LONG_ as long
dim shared LONGINT_ as long
dim shared LOOP_ as long
dim shared LOWORD_ as long
dim shared LPOS_ as long
dim shared LPRINT_ as long
dim shared LSET_ as long
dim shared LTRIM_ as long
dim shared MACRO_ as long
dim shared MID_ as long
dim shared MKD_ as long
dim shared MKDIR_ as long
dim shared MKI_ as long
dim shared MKL_ as long
dim shared MKLONGINT_ as long
dim shared MKS_ as long
dim shared MKSHORT_ as long
dim shared MOD_ as long
dim shared MULTIKEY_ as long
dim shared MUTEXCREATE_ as long
dim shared MUTEXDESTROY_ as long
dim shared MUTEXLOCK_ as long
dim shared MUTEXUNLOCK_ as long
dim shared NAME_ as long
dim shared NAMESPACE_ as long
dim shared NEW_ as long
dim shared NEXT_ as long
dim shared NOT_ as long
dim shared OBJECT_ as long
dim shared OCT_ as long
dim shared OFFSETOF_ as long
dim shared ON_ as long
dim shared OPEN_ as long
dim shared OPERATOR_ as long
dim shared OPTION_ as long
dim shared OR_ as long
dim shared ORELSE_ as long
dim shared OUT_ as long
dim shared OUTPUT_ as long
dim shared OVERLOAD_ as long
dim shared PAINT_ as long
dim shared PALETTE_ as long
dim shared PASCAL_ as long
dim shared PCOPY_ as long
dim shared PEEK_ as long
dim shared PMAP_ as long
dim shared POINT_ as long
dim shared POINTCOORD_ as long
dim shared POINTER_ as long
dim shared POKE_ as long
dim shared POS_ as long
dim shared PRAGMA_ as long
dim shared PRESERVE_ as long
dim shared PRESET_ as long
dim shared PRINT_ as long
dim shared PRIVATE_ as long
dim shared PROCPTR_ as long
dim shared PROPERTY_ as long
dim shared PROTECTED_ as long
dim shared PSET_ as long
dim shared PTR_ as long
dim shared PUBLIC_ as long
dim shared PUT_ as long
dim shared RANDOM_ as long
dim shared RANDOMIZE_ as long
dim shared READ_ as long
dim shared REALLOCATE_ as long
dim shared REDIM_ as long
dim shared REM_ as long
dim shared RESET_ as long
dim shared RESTORE_ as long
dim shared RESUME_ as long
dim shared RETURN_ as long
dim shared RGB_ as long
dim shared RGBA_ as long
dim shared RIGHT_ as long
dim shared RMDIR_ as long
dim shared RND_ as long
dim shared RSET_ as long
dim shared RTRIM_ as long
dim shared RUN_ as long
dim shared SADD_ as long
dim shared SCOPE_ as long
dim shared SCREEN_ as long
dim shared SCREENCONTROL_ as long
dim shared SCREENCOPY_ as long
dim shared SCREENEVENT_ as long
dim shared SCREENGLPROC_ as long
dim shared SCREENINFO_ as long
dim shared SCREENLIST_ as long
dim shared SCREENLOCK_ as long
dim shared SCREENPTR_ as long
dim shared SCREENRES_ as long
dim shared SCREENSET_ as long
dim shared SCREENSYNC_ as long
dim shared SCREENUNLOCK_ as long
dim shared SEEK_ as long
dim shared SELECT_ as long
dim shared SETDATE_ as long
dim shared SETENVIRON_ as long
dim shared SETMOUSE_ as long
dim shared SETTIME_ as long
dim shared SGN_ as long
dim shared SHARED_ as long
dim shared SHELL_ as long
dim shared SHL_ as long
dim shared SHORT_ as long
dim shared SHR_ as long
dim shared SIN_ as long
dim shared SINGLE_ as long
dim shared SIZEOF_ as long
dim shared SLEEP_ as long
dim shared SPACE_ as long
dim shared SPC_ as long
dim shared SQR_ as long
dim shared STATIC_ as long
dim shared STDCALL_ as long
dim shared STEP_ as long
dim shared STOP_ as long
dim shared STR_ as long
dim shared STRING_ as long
dim shared STRPTR_ as long
dim shared SUB_ as long
dim shared SWAP_ as long
dim shared SYSTEM_ as long
dim shared TAB_ as long
dim shared TAN_ as long
dim shared THEN_ as long
dim shared THREADCALL_ as long
dim shared THREADCREATE_ as long
dim shared THREADWAIT_ as long
dim shared TIME_ as long
dim shared TIMER_ as long
dim shared TO_ as long
dim shared TRIM_ as long
dim shared TYPE_ as long
dim shared TYPEOF_ as long
dim shared UBOUND_ as long
dim shared UBYTE_ as long
dim shared UCASE_ as long
dim shared UINTEGER_ as long
dim shared ULONG_ as long
dim shared ULONGINT_ as long
dim shared UNDEF_ as long
dim shared UNION_ as long
dim shared UNLOCK_ as long
dim shared UNSIGNED_ as long
dim shared UNTIL_ as long
dim shared USHORT_ as long
dim shared USING_ as long
dim shared VAL_ as long
dim shared VALINT_ as long
dim shared VALLNG_ as long
dim shared VALUINT_ as long
dim shared VALULNG_ as long
dim shared VAR_ as long
dim shared VARPTR_ as long
dim shared VA_ARG_ as long
dim shared VA_FIRST_ as long
dim shared VA_NEXT_ as long
dim shared VIEW_ as long
dim shared VIRTUAL_ as long
dim shared WAIT_ as long
dim shared WBIN_ as long
dim shared WCHR_ as long
dim shared WEND_ as long
dim shared WHEX_ as long
dim shared WHILE_ as long
dim shared WIDTH_ as long
dim shared WINDOW_ as long
dim shared WINDOWTITLE_ as long
dim shared WINPUT_ as long
dim shared WITH_ as long
dim shared WOCT_ as long
dim shared WRITE_ as long
dim shared WSPACE_ as long
dim shared WSTR_ as long
dim shared WSTRING_ as long
dim shared XOR_ as long
dim shared ZSTRING_ as long
dim shared __DATE_ISO___ as long
dim shared __DATE___ as long
dim shared __FB_BACKEND___ as long
dim shared __FB_BUILD_DATE___ as long
dim shared __FB_DEBUG___ as long
dim shared __FB_ERR___ as long
dim shared __FB_FPMODE___ as long
dim shared __FB_FPU___ as long
dim shared __FB_GCC___ as long
dim shared __FB_LANG___ as long
dim shared __FB_LINUX___ as long
dim shared __FB_MAIN___ as long
dim shared __FB_MIN_VERSION___ as long
dim shared __FB_MT___ as long
dim shared __FB_OPTION_BYVAL___ as long
dim shared __FB_OPTION_DYNAMIC___ as long
dim shared __FB_OPTION_ESCAPE___ as long
dim shared __FB_OPTION_EXPLICIT___ as long
dim shared __FB_OPTION_GOSUB___ as long
dim shared __FB_OPTION_PRIVATE___ as long
dim shared __FB_OUT_DLL___ as long
dim shared __FB_OUT_EXE___ as long
dim shared __FB_OUT_LIB___ as long
dim shared __FB_OUT_OBJ___ as long
dim shared __FB_SIGNATURE___ as long
dim shared __FB_UNIX___ as long
dim shared __FB_VECTORIZE___ as long
dim shared __FB_VERSION___ as long
dim shared __FB_VER_MAJOR___ as long
dim shared __FB_VER_MINOR___ as long
dim shared __FB_VER_PATCH___ as long
dim shared __FILE_NQ___ as long
dim shared __FILE___ as long
dim shared __FUNCTION_NQ___ as long
dim shared __FUNCTION___ as long
dim shared __LINE___ as long
dim shared __PATH___ as long
dim shared __TIME___ as long

#define integer__

enum
	string__
end enum

declare sub open__ alias "open"()

const INT__ = 1
const Int___ = 2

extern     BASE__ alias "BASE" as long
dim shared BASE__ as long
dim shared WINDOW__ as long
extern WINDOWTITLE__ alias "WINDOWTITLE" as long

type Width_
	as_ as long
	type_ as long
	FLOAT as long
	__ as long
end type

type type_ as long

end extern
