#pragma once

'' The following symbols have been renamed:
''     inside struct Width:
''         field __ alias "_"
''     variable ABS_ alias "ABS"
''     variable ABSTRACT_ alias "ABSTRACT"
''     variable ACCESS_ alias "ACCESS"
''     variable ACOS_ alias "ACOS"
''     variable ALIAS_ alias "ALIAS"
''     variable ALLOCATE_ alias "ALLOCATE"
''     variable AND_ alias "AND"
''     variable ANDALSO_ alias "ANDALSO"
''     variable ANY_ alias "ANY"
''     variable APPEND_ alias "APPEND"
''     variable AS_ alias "AS"
''     variable ASC_ alias "ASC"
''     variable ASIN_ alias "ASIN"
''     variable ASM_ alias "ASM"
''     variable ASSERT_ alias "ASSERT"
''     variable ASSERTWARN_ alias "ASSERTWARN"
''     variable ATAN2_ alias "ATAN2"
''     variable ATN_ alias "ATN"
''     variable BASE_ alias "BASE"
''     variable BEEP_ alias "BEEP"
''     variable BIN_ alias "BIN"
''     variable BINARY_ alias "BINARY"
''     variable BIT_ alias "BIT"
''     variable BITRESET_ alias "BITRESET"
''     variable BITSET_ alias "BITSET"
''     variable BLOAD_ alias "BLOAD"
''     variable BSAVE_ alias "BSAVE"
''     variable BYREF_ alias "BYREF"
''     variable BYTE_ alias "BYTE"
''     variable BYVAL_ alias "BYVAL"
''     variable CALL_ alias "CALL"
''     variable CALLOCATE_ alias "CALLOCATE"
''     variable CASE_ alias "CASE"
''     variable CAST_ alias "CAST"
''     variable CBYTE_ alias "CBYTE"
''     variable CDBL_ alias "CDBL"
''     variable CDECL_ alias "CDECL"
''     variable CHAIN_ alias "CHAIN"
''     variable CHDIR_ alias "CHDIR"
''     variable CHR_ alias "CHR"
''     variable CINT_ alias "CINT"
''     variable CIRCLE_ alias "CIRCLE"
''     variable CLASS_ alias "CLASS"
''     variable CLEAR_ alias "CLEAR"
''     variable CLNG_ alias "CLNG"
''     variable CLNGINT_ alias "CLNGINT"
''     variable CLOSE_ alias "CLOSE"
''     variable CLS_ alias "CLS"
''     variable COLOR_ alias "COLOR"
''     variable COMMAND_ alias "COMMAND"
''     variable COMMON_ alias "COMMON"
''     variable CONDBROADCAST_ alias "CONDBROADCAST"
''     variable CONDCREATE_ alias "CONDCREATE"
''     variable CONDDESTROY_ alias "CONDDESTROY"
''     variable CONDSIGNAL_ alias "CONDSIGNAL"
''     variable CONDWAIT_ alias "CONDWAIT"
''     variable CONST_ alias "CONST"
''     variable CONSTRUCTOR_ alias "CONSTRUCTOR"
''     variable CONTINUE_ alias "CONTINUE"
''     variable COS_ alias "COS"
''     variable CPTR_ alias "CPTR"
''     variable CSHORT_ alias "CSHORT"
''     variable CSIGN_ alias "CSIGN"
''     variable CSNG_ alias "CSNG"
''     variable CSRLIN_ alias "CSRLIN"
''     variable CUBYTE_ alias "CUBYTE"
''     variable CUINT_ alias "CUINT"
''     variable CULNG_ alias "CULNG"
''     variable CULNGINT_ alias "CULNGINT"
''     variable CUNSG_ alias "CUNSG"
''     variable CURDIR_ alias "CURDIR"
''     variable CUSHORT_ alias "CUSHORT"
''     variable CVD_ alias "CVD"
''     variable CVI_ alias "CVI"
''     variable CVL_ alias "CVL"
''     variable CVLONGINT_ alias "CVLONGINT"
''     variable CVS_ alias "CVS"
''     variable CVSHORT_ alias "CVSHORT"
''     variable DATA_ alias "DATA"
''     variable DATE_ alias "DATE"
''     variable DEALLOCATE_ alias "DEALLOCATE"
''     variable DECLARE_ alias "DECLARE"
''     variable DEFBYTE_ alias "DEFBYTE"
''     variable DEFDBL_ alias "DEFDBL"
''     variable DEFINE_ alias "DEFINE"
''     variable DEFINED_ alias "DEFINED"
''     variable DEFINT_ alias "DEFINT"
''     variable DEFLNG_ alias "DEFLNG"
''     variable DEFLONGINT_ alias "DEFLONGINT"
''     variable DEFSHORT_ alias "DEFSHORT"
''     variable DEFSNG_ alias "DEFSNG"
''     variable DEFSTR_ alias "DEFSTR"
''     variable DEFUBYTE_ alias "DEFUBYTE"
''     variable DEFUINT_ alias "DEFUINT"
''     variable DEFULNG_ alias "DEFULNG"
''     variable DEFULONGINT_ alias "DEFULONGINT"
''     variable DEFUSHORT_ alias "DEFUSHORT"
''     variable DELETE_ alias "DELETE"
''     variable DESTRUCTOR_ alias "DESTRUCTOR"
''     variable DIM_ alias "DIM"
''     variable DIR_ alias "DIR"
''     variable DO_ alias "DO"
''     variable DOUBLE_ alias "DOUBLE"
''     variable DRAW_ alias "DRAW"
''     variable DYLIBFREE_ alias "DYLIBFREE"
''     variable DYLIBLOAD_ alias "DYLIBLOAD"
''     variable DYLIBSYMBOL_ alias "DYLIBSYMBOL"
''     variable DYNAMIC_ alias "DYNAMIC"
''     variable ELSE_ alias "ELSE"
''     variable ELSEIF_ alias "ELSEIF"
''     variable ENCODING_ alias "ENCODING"
''     variable END_ alias "END"
''     variable ENDIF_ alias "ENDIF"
''     variable ENDMACRO_ alias "ENDMACRO"
''     variable ENUM_ alias "ENUM"
''     variable ENVIRON_ alias "ENVIRON"
''     variable EOF_ alias "EOF"
''     variable EQV_ alias "EQV"
''     variable ERASE_ alias "ERASE"
''     variable ERFN_ alias "ERFN"
''     variable ERL_ alias "ERL"
''     variable ERMN_ alias "ERMN"
''     variable ERR_ alias "ERR"
''     variable ERROR_ alias "ERROR"
''     variable EXEC_ alias "EXEC"
''     variable EXEPATH_ alias "EXEPATH"
''     variable EXIT_ alias "EXIT"
''     variable EXP_ alias "EXP"
''     variable EXPLICIT_ alias "EXPLICIT"
''     variable EXPORT_ alias "EXPORT"
''     variable EXTENDS_ alias "EXTENDS"
''     variable EXTERN_ alias "EXTERN"
''     variable FIELD_ alias "FIELD"
''     variable FIX_ alias "FIX"
''     variable FLIP_ alias "FLIP"
''     variable FOR_ alias "FOR"
''     variable FRAC_ alias "FRAC"
''     variable FRE_ alias "FRE"
''     variable FREEFILE_ alias "FREEFILE"
''     variable FUNCTION_ alias "FUNCTION"
''     variable GET_ alias "GET"
''     variable GETJOYSTICK_ alias "GETJOYSTICK"
''     variable GETKEY_ alias "GETKEY"
''     variable GETMOUSE_ alias "GETMOUSE"
''     variable GOSUB_ alias "GOSUB"
''     variable GOTO_ alias "GOTO"
''     variable HEX_ alias "HEX"
''     variable HIBYTE_ alias "HIBYTE"
''     variable HIWORD_ alias "HIWORD"
''     variable IF_ alias "IF"
''     variable IFDEF_ alias "IFDEF"
''     variable IFNDEF_ alias "IFNDEF"
''     variable IIF_ alias "IIF"
''     variable IMAGECONVERTROW_ alias "IMAGECONVERTROW"
''     variable IMAGECREATE_ alias "IMAGECREATE"
''     variable IMAGEDESTROY_ alias "IMAGEDESTROY"
''     variable IMAGEINFO_ alias "IMAGEINFO"
''     variable IMP_ alias "IMP"
''     variable IMPLEMENTS_ alias "IMPLEMENTS"
''     variable IMPORT_ alias "IMPORT"
''     variable INCLIB_ alias "INCLIB"
''     variable INCLUDE_ alias "INCLUDE"
''     variable INKEY_ alias "INKEY"
''     variable INP_ alias "INP"
''     variable INPUT_ alias "INPUT"
''     variable INSTR_ alias "INSTR"
''     variable INSTRREV_ alias "INSTRREV"
''     variable INT_ alias "INT"
''     variable INTEGER_ alias "INTEGER"
''     variable IS_ alias "IS"
''     variable KILL_ alias "KILL"
''     variable LANG_ alias "LANG"
''     variable LBOUND_ alias "LBOUND"
''     variable LCASE_ alias "LCASE"
''     variable LEFT_ alias "LEFT"
''     variable LEN_ alias "LEN"
''     variable LET_ alias "LET"
''     variable LIB_ alias "LIB"
''     variable LIBPATH_ alias "LIBPATH"
''     variable LINE_ alias "LINE"
''     variable LOBYTE_ alias "LOBYTE"
''     variable LOC_ alias "LOC"
''     variable LOCAL_ alias "LOCAL"
''     variable LOCATE_ alias "LOCATE"
''     variable LOCK_ alias "LOCK"
''     variable LOF_ alias "LOF"
''     variable LOG_ alias "LOG"
''     variable LONG_ alias "LONG"
''     variable LONGINT_ alias "LONGINT"
''     variable LOOP_ alias "LOOP"
''     variable LOWORD_ alias "LOWORD"
''     variable LPOS_ alias "LPOS"
''     variable LPRINT_ alias "LPRINT"
''     variable LSET_ alias "LSET"
''     variable LTRIM_ alias "LTRIM"
''     variable MACRO_ alias "MACRO"
''     variable MID_ alias "MID"
''     variable MKD_ alias "MKD"
''     variable MKDIR_ alias "MKDIR"
''     variable MKI_ alias "MKI"
''     variable MKL_ alias "MKL"
''     variable MKLONGINT_ alias "MKLONGINT"
''     variable MKS_ alias "MKS"
''     variable MKSHORT_ alias "MKSHORT"
''     variable MOD_ alias "MOD"
''     variable MULTIKEY_ alias "MULTIKEY"
''     variable MUTEXCREATE_ alias "MUTEXCREATE"
''     variable MUTEXDESTROY_ alias "MUTEXDESTROY"
''     variable MUTEXLOCK_ alias "MUTEXLOCK"
''     variable MUTEXUNLOCK_ alias "MUTEXUNLOCK"
''     variable NAME_ alias "NAME"
''     variable NAMESPACE_ alias "NAMESPACE"
''     variable NEW_ alias "NEW"
''     variable NEXT_ alias "NEXT"
''     variable NOT_ alias "NOT"
''     variable OBJECT_ alias "OBJECT"
''     variable OCT_ alias "OCT"
''     variable OFFSETOF_ alias "OFFSETOF"
''     variable ON_ alias "ON"
''     variable OPEN_ alias "OPEN"
''     variable OPERATOR_ alias "OPERATOR"
''     variable OPTION_ alias "OPTION"
''     variable OR_ alias "OR"
''     variable ORELSE_ alias "ORELSE"
''     variable OUT_ alias "OUT"
''     variable OUTPUT_ alias "OUTPUT"
''     variable OVERLOAD_ alias "OVERLOAD"
''     variable PAINT_ alias "PAINT"
''     variable PALETTE_ alias "PALETTE"
''     variable PASCAL_ alias "PASCAL"
''     variable PCOPY_ alias "PCOPY"
''     variable PEEK_ alias "PEEK"
''     variable PMAP_ alias "PMAP"
''     variable POINT_ alias "POINT"
''     variable POINTCOORD_ alias "POINTCOORD"
''     variable POINTER_ alias "POINTER"
''     variable POKE_ alias "POKE"
''     variable POS_ alias "POS"
''     variable PRAGMA_ alias "PRAGMA"
''     variable PRESERVE_ alias "PRESERVE"
''     variable PRESET_ alias "PRESET"
''     variable PRINT_ alias "PRINT"
''     variable PRIVATE_ alias "PRIVATE"
''     variable PROCPTR_ alias "PROCPTR"
''     variable PROPERTY_ alias "PROPERTY"
''     variable PROTECTED_ alias "PROTECTED"
''     variable PSET_ alias "PSET"
''     variable PTR_ alias "PTR"
''     variable PUBLIC_ alias "PUBLIC"
''     variable PUT_ alias "PUT"
''     variable RANDOM_ alias "RANDOM"
''     variable RANDOMIZE_ alias "RANDOMIZE"
''     variable READ_ alias "READ"
''     variable REALLOCATE_ alias "REALLOCATE"
''     variable REDIM_ alias "REDIM"
''     variable REM_ alias "REM"
''     variable RESET_ alias "RESET"
''     variable RESTORE_ alias "RESTORE"
''     variable RESUME_ alias "RESUME"
''     variable RETURN_ alias "RETURN"
''     variable RGB_ alias "RGB"
''     variable RGBA_ alias "RGBA"
''     variable RIGHT_ alias "RIGHT"
''     variable RMDIR_ alias "RMDIR"
''     variable RND_ alias "RND"
''     variable RSET_ alias "RSET"
''     variable RTRIM_ alias "RTRIM"
''     variable RUN_ alias "RUN"
''     variable SADD_ alias "SADD"
''     variable SCOPE_ alias "SCOPE"
''     variable SCREEN_ alias "SCREEN"
''     variable SCREENCONTROL_ alias "SCREENCONTROL"
''     variable SCREENCOPY_ alias "SCREENCOPY"
''     variable SCREENEVENT_ alias "SCREENEVENT"
''     variable SCREENGLPROC_ alias "SCREENGLPROC"
''     variable SCREENINFO_ alias "SCREENINFO"
''     variable SCREENLIST_ alias "SCREENLIST"
''     variable SCREENLOCK_ alias "SCREENLOCK"
''     variable SCREENPTR_ alias "SCREENPTR"
''     variable SCREENRES_ alias "SCREENRES"
''     variable SCREENSET_ alias "SCREENSET"
''     variable SCREENSYNC_ alias "SCREENSYNC"
''     variable SCREENUNLOCK_ alias "SCREENUNLOCK"
''     variable SEEK_ alias "SEEK"
''     variable SELECT_ alias "SELECT"
''     variable SETDATE_ alias "SETDATE"
''     variable SETENVIRON_ alias "SETENVIRON"
''     variable SETMOUSE_ alias "SETMOUSE"
''     variable SETTIME_ alias "SETTIME"
''     variable SGN_ alias "SGN"
''     variable SHARED_ alias "SHARED"
''     variable SHELL_ alias "SHELL"
''     variable SHL_ alias "SHL"
''     variable SHORT_ alias "SHORT"
''     variable SHR_ alias "SHR"
''     variable SIN_ alias "SIN"
''     variable SINGLE_ alias "SINGLE"
''     variable SIZEOF_ alias "SIZEOF"
''     variable SLEEP_ alias "SLEEP"
''     variable SPACE_ alias "SPACE"
''     variable SPC_ alias "SPC"
''     variable SQR_ alias "SQR"
''     variable STATIC_ alias "STATIC"
''     variable STDCALL_ alias "STDCALL"
''     variable STEP_ alias "STEP"
''     variable STOP_ alias "STOP"
''     variable STR_ alias "STR"
''     variable STRING_ alias "STRING"
''     variable STRPTR_ alias "STRPTR"
''     variable SUB_ alias "SUB"
''     variable SWAP_ alias "SWAP"
''     variable SYSTEM_ alias "SYSTEM"
''     variable TAB_ alias "TAB"
''     variable TAN_ alias "TAN"
''     variable THEN_ alias "THEN"
''     variable THREADCALL_ alias "THREADCALL"
''     variable THREADCREATE_ alias "THREADCREATE"
''     variable THREADWAIT_ alias "THREADWAIT"
''     variable TIME_ alias "TIME"
''     variable TIMER_ alias "TIMER"
''     variable TO_ alias "TO"
''     variable TRIM_ alias "TRIM"
''     variable TYPE_ alias "TYPE"
''     variable TYPEOF_ alias "TYPEOF"
''     variable UBOUND_ alias "UBOUND"
''     variable UBYTE_ alias "UBYTE"
''     variable UCASE_ alias "UCASE"
''     variable UINTEGER_ alias "UINTEGER"
''     variable ULONG_ alias "ULONG"
''     variable ULONGINT_ alias "ULONGINT"
''     variable UNDEF_ alias "UNDEF"
''     variable UNION_ alias "UNION"
''     variable UNLOCK_ alias "UNLOCK"
''     variable UNSIGNED_ alias "UNSIGNED"
''     variable UNTIL_ alias "UNTIL"
''     variable USHORT_ alias "USHORT"
''     variable USING_ alias "USING"
''     variable VAL_ alias "VAL"
''     variable VALINT_ alias "VALINT"
''     variable VALLNG_ alias "VALLNG"
''     variable VALUINT_ alias "VALUINT"
''     variable VALULNG_ alias "VALULNG"
''     variable VAR_ alias "VAR"
''     variable VARPTR_ alias "VARPTR"
''     variable VA_ARG_ alias "VA_ARG"
''     variable VA_FIRST_ alias "VA_FIRST"
''     variable VA_NEXT_ alias "VA_NEXT"
''     variable VIEW_ alias "VIEW"
''     variable VIRTUAL_ alias "VIRTUAL"
''     variable WAIT_ alias "WAIT"
''     variable WBIN_ alias "WBIN"
''     variable WCHR_ alias "WCHR"
''     variable WEND_ alias "WEND"
''     variable WHEX_ alias "WHEX"
''     variable WHILE_ alias "WHILE"
''     variable WIDTH_ alias "WIDTH"
''     variable WINDOW_ alias "WINDOW"
''     variable WINDOWTITLE_ alias "WINDOWTITLE"
''     variable WINPUT_ alias "WINPUT"
''     variable WITH_ alias "WITH"
''     variable WOCT_ alias "WOCT"
''     variable WRITE_ alias "WRITE"
''     variable WSPACE_ alias "WSPACE"
''     variable WSTR_ alias "WSTR"
''     variable WSTRING_ alias "WSTRING"
''     variable XOR_ alias "XOR"
''     variable ZSTRING_ alias "ZSTRING"
''     variable __DATE_ISO___ alias "__DATE_ISO__"
''     variable __DATE___ alias "__DATE__"
''     variable __FB_BACKEND___ alias "__FB_BACKEND__"
''     variable __FB_BUILD_DATE___ alias "__FB_BUILD_DATE__"
''     variable __FB_DEBUG___ alias "__FB_DEBUG__"
''     variable __FB_ERR___ alias "__FB_ERR__"
''     variable __FB_FPMODE___ alias "__FB_FPMODE__"
''     variable __FB_FPU___ alias "__FB_FPU__"
''     variable __FB_GCC___ alias "__FB_GCC__"
''     variable __FB_LANG___ alias "__FB_LANG__"
''     variable __FB_LINUX___ alias "__FB_LINUX__"
''     variable __FB_MAIN___ alias "__FB_MAIN__"
''     variable __FB_MIN_VERSION___ alias "__FB_MIN_VERSION__"
''     variable __FB_MT___ alias "__FB_MT__"
''     variable __FB_OPTION_BYVAL___ alias "__FB_OPTION_BYVAL__"
''     variable __FB_OPTION_DYNAMIC___ alias "__FB_OPTION_DYNAMIC__"
''     variable __FB_OPTION_ESCAPE___ alias "__FB_OPTION_ESCAPE__"
''     variable __FB_OPTION_EXPLICIT___ alias "__FB_OPTION_EXPLICIT__"
''     variable __FB_OPTION_GOSUB___ alias "__FB_OPTION_GOSUB__"
''     variable __FB_OPTION_PRIVATE___ alias "__FB_OPTION_PRIVATE__"
''     variable __FB_OUT_DLL___ alias "__FB_OUT_DLL__"
''     variable __FB_OUT_EXE___ alias "__FB_OUT_EXE__"
''     variable __FB_OUT_LIB___ alias "__FB_OUT_LIB__"
''     variable __FB_OUT_OBJ___ alias "__FB_OUT_OBJ__"
''     variable __FB_SIGNATURE___ alias "__FB_SIGNATURE__"
''     variable __FB_UNIX___ alias "__FB_UNIX__"
''     variable __FB_VECTORIZE___ alias "__FB_VECTORIZE__"
''     variable __FB_VERSION___ alias "__FB_VERSION__"
''     variable __FB_VER_MAJOR___ alias "__FB_VER_MAJOR__"
''     variable __FB_VER_MINOR___ alias "__FB_VER_MINOR__"
''     variable __FB_VER_PATCH___ alias "__FB_VER_PATCH__"
''     variable __FILE_NQ___ alias "__FILE_NQ__"
''     variable __FILE___ alias "__FILE__"
''     variable __FUNCTION_NQ___ alias "__FUNCTION_NQ__"
''     variable __FUNCTION___ alias "__FUNCTION__"
''     variable __LINE___ alias "__LINE__"
''     variable __PATH___ alias "__PATH__"
''     variable __TIME___ alias "__TIME__"
''     #define integer__ alias "integer"
''     constant string__ alias "string"
''     procedure open__ alias "open"()
''     constant INT__ alias "INT"
''     constant Int___ alias "Int"
''     variable BASE__ alias "BASE"
''     variable WINDOW__ alias "WINDOW"
''     variable WINDOWTITLE__ alias "WINDOWTITLE"
''     struct Width_ alias "Width"
''     typedef type_ alias "type"

extern "C"

dim shared ABS_ as long
dim shared ABSTRACT_ as long
dim shared ACCESS_ as long
dim shared ACOS_ as long
dim shared ALIAS_ as long
dim shared ALLOCATE_ as long
dim shared AND_ as long
dim shared ANDALSO_ as long
dim shared ANY_ as long
dim shared APPEND_ as long
dim shared AS_ as long
dim shared ASC_ as long
dim shared ASIN_ as long
dim shared ASM_ as long
dim shared ASSERT_ as long
dim shared ASSERTWARN_ as long
dim shared ATAN2_ as long
dim shared ATN_ as long
dim shared BASE_ as long
dim shared BEEP_ as long
dim shared BIN_ as long
dim shared BINARY_ as long
dim shared BIT_ as long
dim shared BITRESET_ as long
dim shared BITSET_ as long
dim shared BLOAD_ as long
dim shared BSAVE_ as long
dim shared BYREF_ as long
dim shared BYTE_ as long
dim shared BYVAL_ as long
dim shared CALL_ as long
dim shared CALLOCATE_ as long
dim shared CASE_ as long
dim shared CAST_ as long
dim shared CBYTE_ as long
dim shared CDBL_ as long
dim shared CDECL_ as long
dim shared CHAIN_ as long
dim shared CHDIR_ as long
dim shared CHR_ as long
dim shared CINT_ as long
dim shared CIRCLE_ as long
dim shared CLASS_ as long
dim shared CLEAR_ as long
dim shared CLNG_ as long
dim shared CLNGINT_ as long
dim shared CLOSE_ as long
dim shared CLS_ as long
dim shared COLOR_ as long
dim shared COMMAND_ as long
dim shared COMMON_ as long
dim shared CONDBROADCAST_ as long
dim shared CONDCREATE_ as long
dim shared CONDDESTROY_ as long
dim shared CONDSIGNAL_ as long
dim shared CONDWAIT_ as long
dim shared CONST_ as long
dim shared CONSTRUCTOR_ as long
dim shared CONTINUE_ as long
dim shared COS_ as long
dim shared CPTR_ as long
dim shared CSHORT_ as long
dim shared CSIGN_ as long
dim shared CSNG_ as long
dim shared CSRLIN_ as long
dim shared CUBYTE_ as long
dim shared CUINT_ as long
dim shared CULNG_ as long
dim shared CULNGINT_ as long
dim shared CUNSG_ as long
dim shared CURDIR_ as long
dim shared CUSHORT_ as long
dim shared CVD_ as long
dim shared CVI_ as long
dim shared CVL_ as long
dim shared CVLONGINT_ as long
dim shared CVS_ as long
dim shared CVSHORT_ as long
dim shared DATA_ as long
dim shared DATE_ as long
dim shared DEALLOCATE_ as long
dim shared DECLARE_ as long
dim shared DEFBYTE_ as long
dim shared DEFDBL_ as long
dim shared DEFINE_ as long
dim shared DEFINED_ as long
dim shared DEFINT_ as long
dim shared DEFLNG_ as long
dim shared DEFLONGINT_ as long
dim shared DEFSHORT_ as long
dim shared DEFSNG_ as long
dim shared DEFSTR_ as long
dim shared DEFUBYTE_ as long
dim shared DEFUINT_ as long
dim shared DEFULNG_ as long
dim shared DEFULONGINT_ as long
dim shared DEFUSHORT_ as long
dim shared DELETE_ as long
dim shared DESTRUCTOR_ as long
dim shared DIM_ as long
dim shared DIR_ as long
dim shared DO_ as long
dim shared DOUBLE_ as long
dim shared DRAW_ as long
dim shared DYLIBFREE_ as long
dim shared DYLIBLOAD_ as long
dim shared DYLIBSYMBOL_ as long
dim shared DYNAMIC_ as long
dim shared ELSE_ as long
dim shared ELSEIF_ as long
dim shared ENCODING_ as long
dim shared END_ as long
dim shared ENDIF_ as long
dim shared ENDMACRO_ as long
dim shared ENUM_ as long
dim shared ENVIRON_ as long
dim shared EOF_ as long
dim shared EQV_ as long
dim shared ERASE_ as long
dim shared ERFN_ as long
dim shared ERL_ as long
dim shared ERMN_ as long
dim shared ERR_ as long
dim shared ERROR_ as long
dim shared EXEC_ as long
dim shared EXEPATH_ as long
dim shared EXIT_ as long
dim shared EXP_ as long
dim shared EXPLICIT_ as long
dim shared EXPORT_ as long
dim shared EXTENDS_ as long
dim shared EXTERN_ as long
dim shared FIELD_ as long
dim shared FIX_ as long
dim shared FLIP_ as long
dim shared FOR_ as long
dim shared FRAC_ as long
dim shared FRE_ as long
dim shared FREEFILE_ as long
dim shared FUNCTION_ as long
dim shared GET_ as long
dim shared GETJOYSTICK_ as long
dim shared GETKEY_ as long
dim shared GETMOUSE_ as long
dim shared GOSUB_ as long
dim shared GOTO_ as long
dim shared HEX_ as long
dim shared HIBYTE_ as long
dim shared HIWORD_ as long
dim shared IF_ as long
dim shared IFDEF_ as long
dim shared IFNDEF_ as long
dim shared IIF_ as long
dim shared IMAGECONVERTROW_ as long
dim shared IMAGECREATE_ as long
dim shared IMAGEDESTROY_ as long
dim shared IMAGEINFO_ as long
dim shared IMP_ as long
dim shared IMPLEMENTS_ as long
dim shared IMPORT_ as long
dim shared INCLIB_ as long
dim shared INCLUDE_ as long
dim shared INKEY_ as long
dim shared INP_ as long
dim shared INPUT_ as long
dim shared INSTR_ as long
dim shared INSTRREV_ as long
dim shared INT_ as long
dim shared INTEGER_ as long
dim shared IS_ as long
dim shared KILL_ as long
dim shared LANG_ as long
dim shared LBOUND_ as long
dim shared LCASE_ as long
dim shared LEFT_ as long
dim shared LEN_ as long
dim shared LET_ as long
dim shared LIB_ as long
dim shared LIBPATH_ as long
dim shared LINE_ as long
dim shared LOBYTE_ as long
dim shared LOC_ as long
dim shared LOCAL_ as long
dim shared LOCATE_ as long
dim shared LOCK_ as long
dim shared LOF_ as long
dim shared LOG_ as long
dim shared LONG_ as long
dim shared LONGINT_ as long
dim shared LOOP_ as long
dim shared LOWORD_ as long
dim shared LPOS_ as long
dim shared LPRINT_ as long
dim shared LSET_ as long
dim shared LTRIM_ as long
dim shared MACRO_ as long
dim shared MID_ as long
dim shared MKD_ as long
dim shared MKDIR_ as long
dim shared MKI_ as long
dim shared MKL_ as long
dim shared MKLONGINT_ as long
dim shared MKS_ as long
dim shared MKSHORT_ as long
dim shared MOD_ as long
dim shared MULTIKEY_ as long
dim shared MUTEXCREATE_ as long
dim shared MUTEXDESTROY_ as long
dim shared MUTEXLOCK_ as long
dim shared MUTEXUNLOCK_ as long
dim shared NAME_ as long
dim shared NAMESPACE_ as long
dim shared NEW_ as long
dim shared NEXT_ as long
dim shared NOT_ as long
dim shared OBJECT_ as long
dim shared OCT_ as long
dim shared OFFSETOF_ as long
dim shared ON_ as long
dim shared OPEN_ as long
dim shared OPERATOR_ as long
dim shared OPTION_ as long
dim shared OR_ as long
dim shared ORELSE_ as long
dim shared OUT_ as long
dim shared OUTPUT_ as long
dim shared OVERLOAD_ as long
dim shared PAINT_ as long
dim shared PALETTE_ as long
dim shared PASCAL_ as long
dim shared PCOPY_ as long
dim shared PEEK_ as long
dim shared PMAP_ as long
dim shared POINT_ as long
dim shared POINTCOORD_ as long
dim shared POINTER_ as long
dim shared POKE_ as long
dim shared POS_ as long
dim shared PRAGMA_ as long
dim shared PRESERVE_ as long
dim shared PRESET_ as long
dim shared PRINT_ as long
dim shared PRIVATE_ as long
dim shared PROCPTR_ as long
dim shared PROPERTY_ as long
dim shared PROTECTED_ as long
dim shared PSET_ as long
dim shared PTR_ as long
dim shared PUBLIC_ as long
dim shared PUT_ as long
dim shared RANDOM_ as long
dim shared RANDOMIZE_ as long
dim shared READ_ as long
dim shared REALLOCATE_ as long
dim shared REDIM_ as long
dim shared REM_ as long
dim shared RESET_ as long
dim shared RESTORE_ as long
dim shared RESUME_ as long
dim shared RETURN_ as long
dim shared RGB_ as long
dim shared RGBA_ as long
dim shared RIGHT_ as long
dim shared RMDIR_ as long
dim shared RND_ as long
dim shared RSET_ as long
dim shared RTRIM_ as long
dim shared RUN_ as long
dim shared SADD_ as long
dim shared SCOPE_ as long
dim shared SCREEN_ as long
dim shared SCREENCONTROL_ as long
dim shared SCREENCOPY_ as long
dim shared SCREENEVENT_ as long
dim shared SCREENGLPROC_ as long
dim shared SCREENINFO_ as long
dim shared SCREENLIST_ as long
dim shared SCREENLOCK_ as long
dim shared SCREENPTR_ as long
dim shared SCREENRES_ as long
dim shared SCREENSET_ as long
dim shared SCREENSYNC_ as long
dim shared SCREENUNLOCK_ as long
dim shared SEEK_ as long
dim shared SELECT_ as long
dim shared SETDATE_ as long
dim shared SETENVIRON_ as long
dim shared SETMOUSE_ as long
dim shared SETTIME_ as long
dim shared SGN_ as long
dim shared SHARED_ as long
dim shared SHELL_ as long
dim shared SHL_ as long
dim shared SHORT_ as long
dim shared SHR_ as long
dim shared SIN_ as long
dim shared SINGLE_ as long
dim shared SIZEOF_ as long
dim shared SLEEP_ as long
dim shared SPACE_ as long
dim shared SPC_ as long
dim shared SQR_ as long
dim shared STATIC_ as long
dim shared STDCALL_ as long
dim shared STEP_ as long
dim shared STOP_ as long
dim shared STR_ as long
dim shared STRING_ as long
dim shared STRPTR_ as long
dim shared SUB_ as long
dim shared SWAP_ as long
dim shared SYSTEM_ as long
dim shared TAB_ as long
dim shared TAN_ as long
dim shared THEN_ as long
dim shared THREADCALL_ as long
dim shared THREADCREATE_ as long
dim shared THREADWAIT_ as long
dim shared TIME_ as long
dim shared TIMER_ as long
dim shared TO_ as long
dim shared TRIM_ as long
dim shared TYPE_ as long
dim shared TYPEOF_ as long
dim shared UBOUND_ as long
dim shared UBYTE_ as long
dim shared UCASE_ as long
dim shared UINTEGER_ as long
dim shared ULONG_ as long
dim shared ULONGINT_ as long
dim shared UNDEF_ as long
dim shared UNION_ as long
dim shared UNLOCK_ as long
dim shared UNSIGNED_ as long
dim shared UNTIL_ as long
dim shared USHORT_ as long
dim shared USING_ as long
dim shared VAL_ as long
dim shared VALINT_ as long
dim shared VALLNG_ as long
dim shared VALUINT_ as long
dim shared VALULNG_ as long
dim shared VAR_ as long
dim shared VARPTR_ as long
dim shared VA_ARG_ as long
dim shared VA_FIRST_ as long
dim shared VA_NEXT_ as long
dim shared VIEW_ as long
dim shared VIRTUAL_ as long
dim shared WAIT_ as long
dim shared WBIN_ as long
dim shared WCHR_ as long
dim shared WEND_ as long
dim shared WHEX_ as long
dim shared WHILE_ as long
dim shared WIDTH_ as long
dim shared WINDOW_ as long
dim shared WINDOWTITLE_ as long
dim shared WINPUT_ as long
dim shared WITH_ as long
dim shared WOCT_ as long
dim shared WRITE_ as long
dim shared WSPACE_ as long
dim shared WSTR_ as long
dim shared WSTRING_ as long
dim shared XOR_ as long
dim shared ZSTRING_ as long
dim shared __DATE_ISO___ as long
dim shared __DATE___ as long
dim shared __FB_BACKEND___ as long
dim shared __FB_BUILD_DATE___ as long
dim shared __FB_DEBUG___ as long
dim shared __FB_ERR___ as long
dim shared __FB_FPMODE___ as long
dim shared __FB_FPU___ as long
dim shared __FB_GCC___ as long
dim shared __FB_LANG___ as long
dim shared __FB_LINUX___ as long
dim shared __FB_MAIN___ as long
dim shared __FB_MIN_VERSION___ as long
dim shared __FB_MT___ as long
dim shared __FB_OPTION_BYVAL___ as long
dim shared __FB_OPTION_DYNAMIC___ as long
dim shared __FB_OPTION_ESCAPE___ as long
dim shared __FB_OPTION_EXPLICIT___ as long
dim shared __FB_OPTION_GOSUB___ as long
dim shared __FB_OPTION_PRIVATE___ as long
dim shared __FB_OUT_DLL___ as long
dim shared __FB_OUT_EXE___ as long
dim shared __FB_OUT_LIB___ as long
dim shared __FB_OUT_OBJ___ as long
dim shared __FB_SIGNATURE___ as long
dim shared __FB_UNIX___ as long
dim shared __FB_VECTORIZE___ as long
dim shared __FB_VERSION___ as long
dim shared __FB_VER_MAJOR___ as long
dim shared __FB_VER_MINOR___ as long
dim shared __FB_VER_PATCH___ as long
dim shared __FILE_NQ___ as long
dim shared __FILE___ as long
dim shared __FUNCTION_NQ___ as long
dim shared __FUNCTION___ as long
dim shared __LINE___ as long
dim shared __PATH___ as long
dim shared __TIME___ as long

#define integer__

enum
	string__
end enum

declare sub open__ alias "open"()

const INT__ = 1
const Int___ = 2

extern     BASE__ alias "BASE" as long
dim shared BASE__ as long
dim shared WINDOW__ as long
extern WINDOWTITLE__ alias "WINDOWTITLE" as long

type Width_
	as long as
	as long Static
	as long dim
	as long redim
	as long declare
	as long end
	as long type
	as long Union
	as long Enum
	as long Const
	as long rem
	as long Public
	as long Private
	as long Protected
	inT as long
	If as long
	FLOAT as long
	__ as long
end type

type type_ as long

end extern
