#pragma once

#include once "crt/assert.bi"
#include once "crt/ctype.bi"
#include once "crt/errno.bi"
#include once "crt/float.bi"
#include once "crt/limits.bi"
#include once "crt/locale.bi"
#include once "crt/math.bi"
#include once "crt/setjmp.bi"
#include once "crt/signal.bi"
#include once "crt/stdarg.bi"
#include once "crt/stddef.bi"
#include once "crt/stdint.bi"
#include once "crt/stdio.bi"
#include once "crt/stdlib.bi"
#include once "crt/string.bi"
#include once "crt/time.bi"
#include once "crt/sys/types.bi"
#include once "crt/sys/socket.bi"
#include once "crt/wchar.bi"
