TESTEQ(pathStripExt(""), "")
TESTEQ(pathStripExt("."), "")
TESTEQ(pathStripExt(".h"), "")
TESTEQ(pathStripExt("a"), "a")
TESTEQ(pathStripExt("a."), "a")
TESTEQ(pathStripExt("a.h"), "a")
TESTEQ(pathStripExt("a.h."), "a.h")
TESTEQ(pathStripExt("a.h.h"), "a.h")
TESTEQ(pathStripExt("a.h/a"), "a.h/a")
TESTEQ(pathStripExt("a.h/a.h"), "a.h/a")
TESTEQ(pathStripExt("aaaaaaa/bbbbbbb.ccccccc"), "aaaaaaa/bbbbbbb")


TESTEQ(pathExtOnly(""), "")
TESTEQ(pathExtOnly("."), "")
TESTEQ(pathExtOnly(".h"), "h")
TESTEQ(pathExtOnly("a"), "")
TESTEQ(pathExtOnly("a."), "")
TESTEQ(pathExtOnly("a.h"), "h")
TESTEQ(pathExtOnly("a.h."), "")
TESTEQ(pathExtOnly("a.h.h"), "h")
TESTEQ(pathExtOnly("a.h/a"), "")
TESTEQ(pathExtOnly("a.h/a.h"), "h")
TESTEQ(pathExtOnly("aaaaaaa/bbbbbbb.ccccccc"), "ccccccc")

TESTEQ(pathOnly(""), "")
TESTEQ(pathOnly("a.h"), "")
TESTEQ(pathOnly("foo/a.h"), "foo/")
TESTEQ(pathOnly("/home/me/a.h"), "/home/me/")
TESTEQ(pathOnly("C:/Users/me/a.h"), "C:/Users/me/")

TESTEQ(pathStrip(""), "")
TESTEQ(pathStrip("a.h"), "a.h")
TESTEQ(pathStrip("foo/a.h"), "a.h")
TESTEQ(pathStrip("/home/me/a.h"), "a.h")
TESTEQ(pathStrip("C:/Users/me/a.h"), "a.h")

TESTEQ(pathAddDiv(""), "")
TESTEQ(pathAddDiv("/"), "/")
TESTEQ(pathAddDiv("C:"), "C:" + PATHDIV)
TESTEQ(pathAddDiv("C:/"), "C:/")
TESTEQ(pathAddDiv("/home/foo"), "/home/foo" + PATHDIV)
TESTEQ(pathAddDiv("/home/foo/"), "/home/foo/")
TESTEQ(pathAddDiv("C:/Users/me"), "C:/Users/me" + PATHDIV)
TESTEQ(pathAddDiv("C:/Users/me/"), "C:/Users/me/")

TEST(not pathIsAbsolute("a.h"))
#if defined(__FB_WIN32__) or defined(__FB_DOS__)
	TEST(pathIsAbsolute("C:/a.h"))
#else
	TEST(pathIsAbsolute("/a.h"))
#endif
